### ISSUE TITLE
java.lang.NoClassDefFoundError: alda/error/ExitCode

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda-client-java#38]
Moved from https://github.com/alda-lang/alda-core/issues/68.

Quoth @0atman:

>When I upgraded from 1.0.1 to 1.1.0, with `alda update`, I got this error:
>```java
>Exception in thread "main" java.lang.NoClassDefFoundError: alda/error/ExitCode
>```
>
>However, when I re-run the update, my alda has been updated successfully.

**Comment by daveyarwood** [comment]
I see this happen all the time when I run `alda update`. I think there is probably something weird about the [ExitCode](https://github.com/alda-lang/alda-client-java/blob/master/src/alda/error/ExitCode.java) class in the client, but I don't fully understand the problem. I believe [this](https://github.com/alda-lang/alda-client-java/blob/084f81d/src/alda/Main.java#L380) is the line where it's blowing up.

It's weird, though, because I only seem to see this happen when following the codepath for `alda update`.

Help appreciated here -- NoClassDefFoundError is black magic to me.

**Comment by 0atman** [comment]
Spooky!

**Comment by daveyarwood** [comment]
:ghost:

**Comment by TBuc** [comment]
Couldn't reproduce the issue on Windows 10. I've looked around a little but can't isolate the issue.

Could someone experiencing this issue try to generate an hash of the downloaded alda executable which throws the exception, comparing it to the hash of the working one (i.e. after re-issuing the _update_ command) and see if they match?

**Comment by daveyarwood** [comment]
I know for a fact that the update is successful when you get this error. The JVM is just blowing up when it tries to exit.

**Comment by 0atman** [comment]
Happened again on my celebratory update to 1.3.0, fyi:

```λ ~ alda update
Install alda '1.3.0' over '1.1.0' ? [yN]: y
Downloading https://github.com/alda-lang/alda/releases/download/1.3.0/alda...

Updated alda 1.1.0 => 1.3.0.
If you have any currently running servers, you may want to restart them so that they are running the latest version.
Exception in thread "main" java.lang.NoClassDefFoundError: alda/error/ExitCode
	at alda.Main.main(Main.java:380)
Caused by: java.lang.ClassNotFoundException: alda.error.ExitCode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
λ ~ alda update                                                                                         1
Your version of alda (1.3.0) is up to date!```

**Comment by daveyarwood** [comment]
Alda v2 is implemented in Go, so this issue will go away when Alda v2 is released.
